name: Deploy React App to VPS

on:
  push:
    branches:
      - main  # Chỉnh sửa theo nhánh bạn muốn triển khai

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Hoặc phiên bản Node.js mà bạn cần

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          scp -r build/* user@10.8.0.46:/var/www/idpass.vn
          ssh user@10.8.0.46 "cd /var/www/idpass.vn && pm2 restart your-app-name || pm2 start npm --name your-app-name -- start"
